spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
#    username: sa
#    password:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        default_batch_fetch_size: 100
    open-in-view: false

logging.level:
  org:
    hibernate.SQL: debug
